WEBVTT
Kind: captions
Language: zh-CN

00:00:00.000 --> 00:00:03.359
在此示例中 当执行 try 块时

00:00:03.359 --> 00:00:07.264
对于任何异常 except 块中的代码都会执行

00:00:07.264 --> 00:00:11.309
但是我们只希望处理 valueError 异常

00:00:11.310 --> 00:00:14.600
如果我尝试按下 Ctrl+C 退出程序

00:00:14.599 --> 00:00:19.364
程序并没停止 因为 except 块会处理任何错误

00:00:19.364 --> 00:00:21.664
包括 KeyboardInterrupt 错误

00:00:21.664 --> 00:00:26.280
我们实际上可以像这样明确指定要处理哪个错误

00:00:26.280 --> 00:00:28.770
现在它会捕获 valueError 异常

00:00:28.769 --> 00:00:31.745
但是不会捕获 KeyboardInterrupt 等其他异常

00:00:31.745 --> 00:00:34.814
注意 在这种情况下 当我按下 Ctrl+C 时

00:00:34.814 --> 00:00:36.809
程序会结束

00:00:36.810 --> 00:00:40.185
因为抛出了 KeyboardInterrupt 异常

00:00:40.185 --> 00:00:43.350
而这个 try 语句并没有处理该异常

00:00:43.350 --> 00:00:46.215
此外注意 虽然程序崩溃了

00:00:46.215 --> 00:00:50.010
finally 块中的代码依然执行了

00:00:50.009 --> 00:00:55.585
当程序退出这个 try 语句时 无论是什么原因 都会输出 Attempted Input

00:00:55.585 --> 00:00:57.945
即使退出程序亦如此

00:00:57.945 --> 00:01:02.115
如果我们希望这个处理程序处理多种类型的异常

00:01:02.115 --> 00:01:06.915
我们可以在 except 后面像这样添加一个异常元组

00:01:06.915 --> 00:01:11.865
或者 如果我们希望根据异常处理不同的代码块

00:01:11.864 --> 00:01:15.015
可以像这样添加多个 except 块

00:01:15.015 --> 00:01:17.349
在此示例中 我设定了两个处理程序

00:01:17.349 --> 00:01:20.559
一个针对 valueError 一个针对 KeyboardInterrupt

00:01:20.560 --> 00:01:22.795
当我按下 Ctrl+C 时

00:01:22.795 --> 00:01:26.890
系统提示“No input taken”并退出 while 循环

